# Generated by Django 5.0.7 on 2024-08-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_name_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="photo",
        ),
    ]
