# Generated by Django 5.0.7 on 2024-08-03 07:56

import helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField(validators=[helpers.validators.valid_price])),
                ('description', models.TextField()),
                ('rate', models.FloatField(validators=[helpers.validators.valid_rate])),
            ],
        ),
    ]
