# Generated by Django 5.0.7 on 2024-08-04 10:58

import django.db.models.deletion
import helpers.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('rate', models.CharField(choices=[('10.0', '★★★★★'), ('8.0', '★★★★☆'), ('6.0', '★★★☆☆'), ('3.0', '★★☆☆☆'), ('1.0', '★☆☆☆☆')], max_length=155)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=helpers.storage.upload_producer_logo_image)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
            },
        ),
        migrations.AlterModelOptions(
            name='pizzas',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AddField(
            model_name='pizzas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.storage.upload_pizza_image),
        ),
        migrations.AddField(
            model_name='pizzas',
            name='thick_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('thin', 'Thin'), ('thick', 'Thick'), ('california style', 'California Style'), ('detroit style', ' Detroit Style')], default='classic', max_length=155),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='rate',
            field=models.CharField(choices=[('10.0', '★★★★★'), ('8.0', '★★★★☆'), ('6.0', '★★★☆☆'), ('3.0', '★★☆☆☆'), ('1.0', '★☆☆☆☆')], default='6.0', max_length=155),
        ),
        migrations.AddField(
            model_name='pizzas',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.producers'),
        ),
    ]
