# Generated by Django 5.0.7 on 2024-08-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_producers_alter_pizzas_options_pizzas_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzas',
            name='rate',
            field=models.CharField(choices=[('★★★★★', '★★★★★'), ('★★★★☆', '★★★★☆'), ('★★★☆☆', '★★★☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★☆☆☆☆', '★☆☆☆☆')], default='6.0', max_length=155),
        ),
        migrations.AlterField(
            model_name='producers',
            name='rate',
            field=models.CharField(choices=[('★★★★★', '★★★★★'), ('★★★★☆', '★★★★☆'), ('★★★☆☆', '★★★☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★☆☆☆☆', '★☆☆☆☆')], max_length=155),
        ),
    ]
