# Generated by Django 5.0.7 on 2024-08-12 09:14

import django.db.models.deletion
import helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0003_alter_pizzas_rate_alter_producers_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizzas",
            name="price",
            field=models.PositiveIntegerField(
                validators=[helpers.validators.valid_price]
            ),
        ),
        migrations.AlterField(
            model_name="pizzas",
            name="producer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pizzas",
                to="main_page.producers",
            ),
        ),
    ]
