# Generated by Django 5.0.7 on 2024-08-12 10:18

import django.db.models.deletion
import helpers.storage
import helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main_page", "0004_alter_pizzas_price_alter_pizzas_producer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Burger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "price",
                    models.PositiveIntegerField(
                        validators=[helpers.validators.valid_price]
                    ),
                ),
                ("description", models.TextField()),
                (
                    "rate",
                    models.CharField(
                        choices=[
                            ("★★★★★", "★★★★★"),
                            ("★★★★☆", "★★★★☆"),
                            ("★★★☆☆", "★★★☆☆"),
                            ("★★☆☆☆", "★★☆☆☆"),
                            ("★☆☆☆☆", "★☆☆☆☆"),
                        ],
                        default="6.0",
                        max_length=155,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=helpers.storage.upload_burger_image,
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="burger",
                        to="main_page.producers",
                    ),
                ),
            ],
        ),
    ]
